---
#PURPOSE: Playbook to update the nic info for test & prod builds
- name: NIC FILE UPDATE FOR BUILDS
  hosts: ERP
  gather_facts: yes
  user: rjoy
  become: true

  environment:
    PATH: '/usr/sbin:/sbin:/usr/bin:/bin'

  vars:
    basedir_ERP: '/home/rjoy/ansible/ERP_STOR_NIC/'

  tasks:
    - name: Define file to copy for ERP
      copy: 
        src: '{{ basedir_ERP }}'
        dest: /etc/sysconfig/network-scripts/ 

