---
- name: Playbook for resizing the partition
  hosts: erp
  gather_facts: no
  user: rjoy
  become: true
  tasks:
    - name: sort the mounts
      shell: df -h | sort
      register: result
    - debug: var=result
