---
- hosts: sandbox
  user: rjoy
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Remove users
    user: name={{ item }} state=absent
    with_items:
    - user1
    - user2
    - user3
