---
- hosts: sandbox
  user: rjoy
  become: yes
  gather_facts: yes
  tasks:
    - name: Date/Time stamp when the playbook starts
      raw: /bin/date > /tmp/playbook_start.log
    - name: Install the apache webserver
      yum: pkg=httpd state=latest
    - name: start the web service
      service: name=httpd state=restarted
    - name: Verify that the web service is running
      command: systemctl status httpd
      register: result
    - debug: var=result
    - name: Install client software
      yum: pkg=telnet state=latest
      yum: pkg=lynx state=latest
    - name: Log all the packages installed on the system
      raw: yum list installed > /tmp/installed.log
    - name: date/time stamp when the playbook ends
      raw: /bin/date > /tmp/playbook_end.log
