---
- hosts: sandbox
  user: rjoy
  become: yes
  gather_facts: yes
  tasks:
    - name: Date/Time stamp when the playbook starts
      command: /bin/date
      register: timestamp_start
    - debug: var=timestamp_start
    - name: Install the apache webserver
      yum: pkg=httpd state=latest
